import { formatTimestamp, stripMarkup, type Cue } from './model';

export function writeSrt(cues: Cue[]): string {
  return (
    cues
      .map((c, i) => {
        const pos = c.settings && /line:0\b/.test(c.settings) ? '{\\an8}' : '';
        return `${i + 1}\r\n${formatTimestamp(c.start, 'srt')} --> ${formatTimestamp(c.end, 'srt')}\r\n${pos}${c.text.replace(/\n/g, '\r\n')}`;
      })
      .join('\r\n\r\n') + '\r\n'
  );
}

function escapeVtt(text: string): string {
  return text
    .split(/(<\/?[ibu]>)/)
    .map((part, i) => (i % 2 ? part : part.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')))
    .join('');
}

export function writeVtt(cues: Cue[]): string {
  const body = cues
    .map((c) => {
      const settings = c.settings ? ` ${c.settings}` : '';
      // A cue line must not be blank inside the payload; replace empty lines with a space-less NBSP.
      const text = escapeVtt(c.text)
        .split('\n')
        .map((l) => (l.trim() ? l : ' '))
        .join('\n');
      return `${formatTimestamp(c.start, 'vtt')} --> ${formatTimestamp(c.end, 'vtt')}${settings}\n${text}`;
    })
    .join('\n\n');
  return `WEBVTT\n\n${body}\n`;
}

export interface AssOptions {
  fontName: string;
  fontSize: number;
  width: number;
  height: number;
}

export function markupToAss(text: string): string {
  return text
    .replace(/\{/g, '(')
    .replace(/\}/g, ')')
    .replace(/<([ibu])>/g, '{\\$11}')
    .replace(/<\/([ibu])>/g, '{\\$10}')
    .replace(/\n/g, '\\N');
}

export function writeAss(cues: Cue[], o: AssOptions): string {
  const font = o.fontName.replace(/[,\r\n]/g, ' ').trim() || 'Arial';
  const marginV = Math.round(o.height * 0.04);
  const marginH = Math.round(o.width * 0.05);
  const outline = Math.max(1, Math.round(o.fontSize / 24));
  const events = cues.map((c) => {
    const top = c.settings && /line:0\b/.test(c.settings) ? '{\\an8}' : '';
    return `Dialogue: 0,${formatTimestamp(c.start, 'ass')},${formatTimestamp(c.end, 'ass')},Default,,0,0,0,,${top}${markupToAss(c.text)}`;
  });
  return `[Script Info]
; Script generated by Formatoza
Title: Converted subtitles
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None
PlayResX: ${o.width}
PlayResY: ${o.height}

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,${font},${o.fontSize},&H00FFFFFF,&H000000FF,&H00000000,&H80000000,0,0,0,0,100,100,0,0,1,${outline},${Math.max(0, outline - 1)},2,${marginH},${marginH},${marginV},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
${events.join('\n')}
`;
}

export interface TxtOptions {
  timestamps: boolean;
  paragraphs: boolean;
  dedupe: boolean;
}

const PARAGRAPH_GAP_MS = 2000;

export function writeTxt(cues: Cue[], o: TxtOptions): string {
  const plain = (c: Cue) =>
    stripMarkup(c.text)
      .split('\n')
      .map((l) => l.replace(/ /g, ' ').trim())
      .filter(Boolean);

  if (o.timestamps) {
    return (
      cues
        .map((c) => `[${formatTimestamp(c.start, 'txt')}] ${plain(c).join(' ')}`)
        .filter((l, i, all) => !o.dedupe || l.slice(l.indexOf(']')) !== all[i - 1]?.slice(all[i - 1]!.indexOf(']')))
        .join('\n') + '\n'
    );
  }

  // Line-level de-duplication handles "rolling" auto-captions, where each cue
  // repeats the previous cue's last line.
  const units: { text: string; start: number; end: number }[] = [];
  let lastLine = '';
  for (const c of cues) {
    for (const line of plain(c)) {
      if (o.dedupe && line === lastLine) continue;
      units.push({ text: line, start: c.start, end: c.end });
      lastLine = line;
    }
  }
  if (!o.paragraphs) return units.map((u) => u.text).join('\n') + '\n';

  const paragraphs: string[] = [];
  let current: string[] = [];
  let prevEnd = -Infinity;
  for (const u of units) {
    const speakerChange = /^(-|–|—|>>)\s*/.test(u.text);
    if (current.length && (u.start - prevEnd >= PARAGRAPH_GAP_MS || speakerChange)) {
      paragraphs.push(current.join(' '));
      current = [];
    }
    current.push(u.text);
    prevEnd = Math.max(prevEnd, u.end);
  }
  if (current.length) paragraphs.push(current.join(' '));
  return paragraphs.join('\n\n') + '\n';
}
